# Generated by Django 3.1 on 2020-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.URLField(max_length=5000),
        ),
    ]
