# Generated by Django 3.1 on 2020-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0002_auto_20200826_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('vid', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
