# Generated by Django 3.1 on 2020-08-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0003_auto_20200826_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socket',
            name='topic',
        ),
        migrations.AddField(
            model_name='socket',
            name='numb',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='socket',
            name='vid',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
