# Generated by Django 3.1 on 2020-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0004_auto_20200826_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='numb',
            field=models.IntegerField(default=0),
        ),
    ]
