# Generated by Django 3.1 on 2020-08-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0005_auto_20200826_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='client',
            field=models.CharField(default=0, max_length=10000),
        ),
        migrations.AddField(
            model_name='socket',
            name='server',
            field=models.CharField(default=0, max_length=10000),
        ),
    ]
