# Generated by Django 3.1 on 2020-08-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0006_auto_20200826_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gitandvsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField(default=0)),
                ('vid', models.CharField(default=0, max_length=5000)),
                ('md', models.CharField(max_length=10000)),
            ],
        ),
    ]
