# Generated by Django 3.1 on 2020-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0008_auto_20200827_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='file1',
            field=models.CharField(default=0, max_length=10000),
        ),
    ]
