# Generated by Django 3.1 on 2020-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0009_socket_file1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pygame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField(default=0)),
                ('vid', models.CharField(default=0, max_length=500)),
                ('name1', models.CharField(default=0, max_length=10)),
                ('file1', models.CharField(default=0, max_length=10000)),
            ],
        ),
    ]
