# Generated by Django 3.1 on 2020-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0011_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='option',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='did',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ied',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
