# Generated by Django 3.1 on 2020-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0012_auto_20200901_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='did',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ied',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='option',
            field=models.CharField(max_length=10),
        ),
    ]
