# Generated by Django 3.1 on 2020-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0013_auto_20200901_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='option',
            field=models.CharField(max_length=50),
        ),
    ]
