# Generated by Django 3.1 on 2020-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0015_remove_pygame_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pygame',
            name='name1',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
