# Generated by Django 3.1 on 2020-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navig', '0016_pygame_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dat5',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='did',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
